name: "deploy website"
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
  workflow_dispatch:
jobs:
    create-folder:
        name: Create folder on Server
        runs-on: ubuntu-latest
        steps:
          - name: Creer un repertoire sur le server
            uses: appleboy/ssh-action@v1
            with:
              host: ${{ secrets.SERVER_HOST }}
              username: ${{ secrets.SERVER_USERNAME }}
              key: ${{ secrets.SERVER_SSH_PRIVATE_KEY}}
              port: ${{ secrets.SERVER_PORT }}
              script: |
                mkdir -p /opt/mes-naissances/mesnaissancesxcdcv
    build-project:
        runs-on: ubuntu-latest
        needs:
            - create-folder
        steps:
            - name: check out repository code
              uses: actions/checkout@v4
            - name: build project
              run: |
                npm install
                npm run build
            - name: copy file on server 
              uses: appleboy/scp-action@v1
              with:
                host: ${{ secrets.SERVER_HOST }}
                username: ${{ secrets.SERVER_USERNAME }}
                key: ${{ secrets.SERVER_SSH_PRIVATE_KEY}}
                port: ${{ secrets.SERVER_PORT }}
                source: dist
                target: /opt/mes-naissances/mesnaissancesxcdcv
                strip_components: 1
                overwrite: true
    run-project:
        name: run project
        runs-on: ubuntu-latest
        needs: build-project
        steps:
            - name: check out repository code
              uses: actions/checkout@v4
            - name: copy configuration files on server 
              uses: appleboy/scp-action@v1
              with:
                host: ${{ secrets.SERVER_HOST }}
                username: ${{ secrets.SERVER_USERNAME }}
                key: ${{ secrets.SERVER_SSH_PRIVATE_KEY}}
                port: ${{ secrets.SERVER_PORT }}
                source: website.conf
                target: /etc/nginx/conf.d
                overwrite: true
            - name: Executer le projet
              uses: appleboy/ssh-action@v1.2.0
              with:
                host: ${{ secrets.SERVER_HOST }}
                username: ${{ secrets.SERVER_USERNAME }}
                key: ${{ secrets.SERVER_SSH_PRIVATE_KEY}}
                port: ${{ secrets.SERVER_PORT }}
                script: |
                    nginx -t
                    service nginx restart
                    certbot certonly --nginx -d msnaissance.xcdcv.site --force-renew
